baseURL = "https://haydenhousen.com/"
languageCode = "en-us"
title = "Hayden Housen"
theme = "resume"
disableKinds = ["RSS"]
enableRobotsTXT = true
enableGitInfo = true

[taxonomies]
  tag = "tags"

[params]
  firstName = "Hayden"
  lastName = "Housen"
  address = "San Francisco, CA"
  profileImage = "media/hh-logo.png"
  gitCommitPrefix = "https://github.com/HHousen/hh-personal"
  email = "hayden@haydenhousen.com"
  description = "Co-founder at Sonauto (YC W24). Studied computer science at Cornell University. Previously, a software engineering intern at Vocode (YC W23) and an intern on the Machine Learning Team at Ada."
  favicon = "media/favicon.png"
  resumePDF = "media/Hayden_Housen_Resume_v4.6.pdf"
  # what sections
  showSkills = true
  showProjects = true
  tags = ["DevOps", "Web Development", "Machine Learning", "Cyber Security"]
  showContributions = false
  showPublications = false
  showExperience = true
  showEducation = true


[params.google_analytics]
  trackerID = "UA-55408421-8"

[[params.social]]
  name = "GitHub"
  icon = "icon-github"
  link = "https://github.com/HHousen"

[[params.social]]
  name = "LinkedIn"
  icon = "icon-linkedin-square"
  link = "https://linkedin.com/in/HHousen"

[[params.social]]
  name = "Email"
  icon = "icon-envelope"
  link = "mailto:hayde-remove-n@haydenhousen.com"
