baseURL = "https://haydenhousen.com/"
languageCode = "en-us"
title = "Hayden Housen - Student Developer"
theme = "resume"
disableKinds = ["RSS"]
enableRobotsTXT = true
enableGitInfo = true

[taxonomies]
  tag = "tags"

[params]
  firstName = "Hayden"
  lastName = "Housen"
  address = "Pawling, NY"
  profileImage = "media/hh-logo.png"
  gitCommitPrefix = "https://github.com/HHousen/hh-personal"
  email = "hayden@haydenhousen.com"
  description = "A logical and detail-oriented high school senior with extensive experience in computer science. Currently is researching automatic classroom lecture summarization using AI and Deep Learning. Understands machine learning in production and full-stack web development. Maintains open-source NLP programs that perform state-of-the-art neural text summarization. Publishes guides for cybersecurity challenges. Enjoys running cross country in the fall and skiing in the winter."
  favicon = "media/favicon.png"
  resumePDF = "media/Hayden_Housen_Resume_V3.2.pdf"
  # what sections
  showSkills = true
  showProjects = true
  tags = ["DevOps", "Web Development", "Machine Learning", "App Development", "Cyber Security"]
  showContributions = false
  showPublications = false
  showExperience = true
  showEducation = true


[params.google_analytics]
  trackerID = "UA-55408421-8"



[[params.social]]
  name = "CodePen"
  icon = "fab fa-codepen"
  link = "https://codepen.io/HHousen"

[[params.social]]
  name = "Sourcerer"
  icon = "fas fa-code-branch"
  link = "https://sourcerer.io/HHousen"

[[params.social]]
  name = "Twitter"
  icon = "fab fa-twitter"
  link = "https://twitter.com/thehaydenhousen"

[[params.social]]
  name = "Github"
  icon = "fab fa-github"
  link = "https://github.com/HHousen"

[[params.social]]
  name = "Email"
  icon = "fas fa-envelope"
  link = "mailto:hayden@haydenhousen.com"
