baseURL = "https://haydenhousen.com/"
languageCode = "en-us"
title = "Hayden Housen - Student Developer"
theme = "resume"
disableKinds = ["RSS"]
enableRobotsTXT = true
enableGitInfo = true

[taxonomies]
  tag = "tags"

[params]
    firstName = "Hayden"
    lastName = "Housen"
    address = "Pawling, NY"
    profileImage = "img/hh-logo.png"
    gitCommitPrefix = "https://github.com/HHousen/hh-personal"
    email = "hayden@haydenhousen.com"
    description = "High school junior with extensive experience in computer science. Possesses impeccable organizational skills and excellent knowledge of programming languages. Is a diligent and dedicated individual that never gives up. Currently is conducting research in the fields of machine learning and computer vision. Enjoys running cross country in the fall and skiing in the winter."
    favicon = "img/favicon.png"
    resumePDF = "pdf/Hayden_Housen_Resume_V2.0.pdf"
    # what sections
    showSkills = true
    showProjects = true
    tags = ["DevOps", "Web Development", "Machine Learning", "App Development", "Cyber Security"]
    showContributions = false
    showPublications = false
    showExperience = true
    showEducation = true


[params.google_analytics]
    trackerID = "UA-55408421-8"



[[params.social]]
  name = "CodePen"
  icon = "fab fa-codepen"
  link = "https://codepen.io/HHousen"

[[params.social]]
  name = "Twitter"
  icon = "fab fa-twitter"
  link = "https://twitter.com/thehaydenhousen"

[[params.social]]
  name = "Github"
  icon = "fab fa-github"
  link = "https://github.com/HHousen"

[[params.social]]
  name = "Email"
  icon = "fas fa-envelope"
  link = "mailto:hayden@haydenhousen.com"
