baseURL = "https://haydenhousen.com/"
languageCode = "en-us"
title = "Hayden Housen | Student Developer"
theme = "aerial"

[params]
  name = "Hayden Housen"
  about = "Student Pawling High School &nbsp;&bull;&nbsp; Programmer & Developer &nbsp;&bull;&nbsp; Diligent Worker"
  copyright = "Hayden Housen"
  #Disable the scrolling background by entering any string for bg_scroll. Enable by leaving bg_scroll empty.
  bg_scroll = ""
  favicon = "favicon.png"

[[params.social]]
  medium = "Twitter"
  icon = "twitter"
  link = "https://twitter.com/thehaydenhousen"

[[params.social]]
  medium = "CodePen"
  icon = "codepen"
  link = "https://codepen.io/HHousen"

[[params.social]]
  medium = "Github"
  icon = "github"
  link = "https://github.com/HHousen"

[[params.social]]
  medium = "Email"
  icon = "envelope-o"
  link = "mailto:hayden@haydenhousen.com"
