baseURL = "https://haydenhousen.com/"
languageCode = "en-us"
title = "Hayden Housen | Student Developer"
theme = "resume"
disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]
enableRobotsTXT = true

[params]
    firstName = "Hayden"
    lastName = "Housen"
    address = "Pawling, NY"
    profileImage = "img/hh-logo.png"
    email = "hayden@haydenhousen.com"
    description = "Software Platform Engineer with experience leveraging agile, DevOps, and CI/CD to manage large scale distributed platforms both on prem and in public cloud."
    favicon = "img/favicon.png"
    # what sections
    showSkills = true
    showProjects = true
    showOpenSource = true
    showPublications = true
    showExperience = true
    showEducation = true


[params.google_analytics]
    trackerID = ""



[[params.social]]
  name = "CodePen"
  icon = "fab fa-codepen"
  link = "https://codepen.io/HHousen"

[[params.social]]
  name = "Twitter"
  icon = "fab fa-twitter"
  link = "https://twitter.com/thehaydenhousen"

[[params.social]]
  name = "Github"
  icon = "fab fa-github"
  link = "https://github.com/HHousen"

[[params.social]]
  name = "Email"
  icon = "fas fa-envelope"
  link = "mailto:hayden@haydenhousen.com"
